theme: jekyll-theme-leap-day
title: Scientific Software Registry Collaboration Workshop
description: A Sloan Foundation-funded workshop for editors & maintainers of academic discipline & institutional software registries & repositories
